# Generated by Django 4.2.4 on 2023-09-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudmodel',
            options={'verbose_name': 'Crud', 'verbose_name_plural': "CRUD'S"},
        ),
        migrations.RemoveField(
            model_name='crudmodel',
            name='image',
        ),
    ]
