# Generated by Django 4.2.4 on 2023-09-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_crudmodel_options_remove_crudmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='photos/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud_app.crudmodel')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
