# Generated by Django 4.2.4 on 2023-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_remove_profilemodel_user_crudmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/images'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
