# Generated by Django 4.2.4 on 2023-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_alter_crudmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='crudmodel',
            name='image',
            field=models.ImageField(default='photos/images/photo.jpg', null=True, upload_to='photos/images'),
        ),
    ]
